### ISSUE TITLE
Error running ConsulDemocracy after following the installation docs on macOS

### ISSUE THREAD

**Issue by emothek** [consuldemocracy/consuldemocracy#5656] opened 2024-08-19 00:52 UTC
<header role="banner" style="color: rgb(240, 240, 240); background: rgb(204, 0, 0); padding: 0.5em 1.5em; font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="overflow-wrap: break-word; margin: 0.2em 0px; line-height: 1.1em; font-size: 2em;">SassC::SyntaxError in Welcome#index</h1></header><main role="main" id="container" style="box-sizing: border-box; width: 893px; padding: 0px 1.5em; color: rgb(236, 236, 236); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-bottom: 0px;"><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;">Showing<span> </span><i>/Users/mokhtarmegherbi/gov/consuldemocracy/app/views/layouts/_common_head.html.erb</i><span> </span>where line<span> </span><b>#9</b><span> </span>raised:</p><pre style="font-size: 11px; white-space: pre-wrap;"><code>Error: Can't find stylesheet to import.
[34m  ╷[0m
[34m1 │[0m @import [31m"sassc-embedded-import:273"[0m;
[34m  │[0m [31m        ^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
[34m  ╵[0m
  sassc-embedded-import:272 1:9                                                            @import
  sassc-embedded-import:foundation_and_overrides.scss 10:9                                 @import
  sassc-embedded-import:32 1:9                                                             @import
  /Users/mokhtarmegherbi/gov/consuldemocracy/app/assets/stylesheets/application.scss 18:9  root stylesheet</code></pre><div class="source " id="frame-source-0-60" style="border: 1px solid rgb(85, 85, 85); background: rgb(51, 51, 51); max-width: 978px;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#9</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(68, 68, 68);">
7 8 9 10 11 12 | <%= stylesheet_link_tag "application-rtl" %> <% else %>   <%= stylesheet_link_tag "application" %> <% end %> <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %> <%= csrf_meta_tags %>
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;">Trace of template inclusion: #&lt;ActionView::Template app/views/layouts/application.html.erb locals=[]&gt;</p><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><code>Rails.root: /Users/mokhtarmegherbi/gov/consuldemocracy</code></p><div id="traces-0"><a href="http://127.0.0.1:3000/#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Application Trace</a><span> </span>|<span> </span><a href="http://127.0.0.1:3000/#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Framework Trace</a><span> </span>|<span> </span><a href="http://127.0.0.1:3000/#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(204, 0, 0);">Full Trace</a><div id="Application-Trace-0" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="189620" data-frame-id="60" href="http://127.0.0.1:3000/#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/views/layouts/_common_head.html.erb:9</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="189620" data-frame-id="76" href="http://127.0.0.1:3000/#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/views/layouts/application.html.erb:4</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="189620" data-frame-id="116" href="http://127.0.0.1:3000/#" style="color: rgb(153, 153, 153); overflow-wrap: break-word;">app/controllers/application_controller.rb:50:in `switch_locale'</a></code></div></div></main>SassC::SyntaxError in Welcome#index
Showing /Users/mokhtarmegherbi/gov/consuldemocracy/app/views/layouts/_common_head.html.erb where line #9 raised:

Error: Can't find stylesheet to import.
[34m  ╷[0m
[34m1 │[0m @import [31m"sassc-embedded-import:273"[0m;
[34m  │[0m [31m        ^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
[34m  ╵[0m
  sassc-embedded-import:272 1:9                                                            @import
  sassc-embedded-import:foundation_and_overrides.scss 10:9                                 @import
  sassc-embedded-import:32 1:9                                                             @import
  /Users/mokhtarmegherbi/gov/consuldemocracy/app/assets/stylesheets/application.scss 18:9  root stylesheet
Extracted source (around line #9):
7
8
9
10
11
12
              
  <%= stylesheet_link_tag "application-rtl" %>
<% else %>
  <%= stylesheet_link_tag "application" %>
<% end %>
<%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
<%= csrf_meta_tags %>

Trace of template inclusion: #<ActionView::Template app/views/layouts/application.html.erb locals=[]>

Rails.root: /Users/mokhtarmegherbi/gov/consuldemocracy

[Application Trace](http://127.0.0.1:3000/#) | [Framework Trace](http://127.0.0.1:3000/#) | [Full Trace](http://127.0.0.1:3000/#)
[app/views/layouts/_common_head.html.erb:9](http://127.0.0.1:3000/#)
[app/views/layouts/application.html.erb:4](http://127.0.0.1:3000/#)
[app/controllers/application_controller.rb:50:in `switch_locale'](http://127.0.0.1:3000/#)

**Comment by javierm** [comment] 2024-08-19 11:34
Hi, @emothek :smile:.

This might be a duplicate of #5490 :thinking:. Have you run `bin/setup` (or `npm install`)?

**Comment by emothek** [comment] 2024-08-19 11:37
Hi, thanks for reply 

I have followed the steps properly , including sudo bin/setup , so what I understood is that that missing sass file is not there , is it failing build ? Or am I missing to run npm install , even ..

**Comment by javierm** [comment] 2024-08-19 11:52
> including sudo bin/setup

Not that `sudo` isn't necessary in any of the [local installation steps](https://docs.consuldemocracy.org/tech_docs/introduction/local_installation) (once the prerriquisites are installed). Not sure whether that might be causing the error :thinking:.

Could you check the conversation in #5490 and see whether the suggestions there help?

Moving the conversation to #5490.

**Closed by javierm** 2024-08-19 11:52 UTC
